# Site configuration
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: custom

# Site settings
title: "Gem County Runners"
logo: "/assets/images/gcr-822x822.png"
masthead_title: " "
description: "Improving lives and the community, one run at a time."
author: Taylor
locale: en-US

url: "https://gemcounty.run"
baseurl: ""

# Fonts (Google Fonts)
google_fonts:
  - Montserrat:400,700
  - Roboto+Slab:400,700
  - Quicksand:400,700

# Plugins (only those supported by GitHub Pages)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Breadcrumbs
breadcrumbs:
  enabled: true

# SEO + Social Metadata
seo:
  type: Organization
  name: Gem County Runners
  description: "A runner-led community in Emmett, Idaho."

social:
  type: Person
  links:
    - https://www.strava.com/clubs/gemcountyrunners
    - https://instagram.com/gemcountyrunners

# Footer links
footer:
  links:
    - label: "Strava Club"
      icon: "fab fa-strava"
      url: "https://www.strava.com/clubs/gemcountyrunners"
    - label: "Instagram Journey"
      icon: "fab fa-instagram"
      url: "https://instagram.com/gemcountyrunners"
    - label: "Local Recreation"
      icon: "fa-solid fa-person-walking"
      url: "https://www.gemcountyrecreation.com"

# Atom Feed
atom_feed:
  hide: true

# Include Paths
include:
  - .htaccess
  - _pages
  - _includes/head-custom.html
