# Site configuration
# Documentation: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#general-configuration
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: custom # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
title: "Gem County Runners"
logo: "/assets/images/gcr-822x822.png"

# Fonts (Google Fonts)
google_fonts:
  - Montserrat:400,700
  - Roboto+Slab:400,700
  - Quicksand:400,700
masthead_title: " "
description: "Improving lives and the community, one run at a time."
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

breadcrumbs:
  enabled: true

social:
  type: Person
  links:
    - https://www.strava.com/clubs/gemcountyrunners
    - https://instagram.com/gemcountyrunners

footer:
  links:
    - label: "Strava Club"
      icon: "fab fa-strava"
      url: "https://www.strava.com/clubs/gemcountyrunners"
    - label: "Instagram Journey"
      icon: "fab fa-instagram"
      url: "https://instagram.com/gemcountyrunners"
    - label: "Local Recreation"
      icon: "fa-solid fa-person-walking"
      url: "https://www.gemcountyrecreation.com"

atom_feed:
  hide: true

include:
  - .htaccess
  - _pages
  - _includes/head-custom.html
