# Site configuration
# Documentation: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#general-configuration
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
title: "Gem County Runners"
logo: "/assets/images/gcr-822x822.png"
masthead_title: " "
description: "Improving lives and the community, one run at a time."
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

breadcrumbs:
  enabled: true

social:
  type: Person
  links:
    - https://www.strava.com/clubs/gemcountyrunners
    - https://instagram.com/gemcountyrunners

footer:
  links:
    - label: "Strava"
      icon: "fab fa-brands fa-strava"
      url: "https://www.strava.com/clubs/gemcountyrunners"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gemcountyrunners"
    label: GCRD
    icon: "fa-duotone fa-solid fa-bell-concierge"
    url: "https://www.gemcountyrecreation.com"

atom_feed:
  hide: true

include:
  - .htaccess
  - _pages
