# Site configuration

# theme repo: https://github.com/mmistakes/so-simple-theme
remote_theme: mmistakes/so-simple-theme

title: 'Gem County Runners'
description: "A simple Jekyll theme for words and pictures."
share: true
