# Site configuration

# theme repo: https://github.com/mmistakes/so-simple-theme
remote_theme: mmistakes/so-simple-theme

title: 'Gem County Runners'
description: "Improving lives and the community, one run at a time."
share: true
